package com.heang.springmybatistest.mapper;

import com.heang.springmybatistest.vo.BgtMngInVO;
import com.heang.springmybatistest.vo.BgtMngOutVO;
import com.heang.springmybatistest.vo.BgtMngVO;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

/**
 * BgtMngMapper — MyBatis Mapper interface for Budget Management (예산 관리 매퍼)
 *
 * How MyBatis works:
 *   1) You define method signatures here (Java interface — no implementation needed)
 *   2) SQL is written in BgtMngMapper.xml (same method name = same <select/insert/update> id)
 *   3) MyBatis creates a proxy at runtime that connects the method to the SQL
 *   4) Spring injects this interface wherever it is used (@RequiredArgsConstructor)
 *
 * @Mapper → tells MyBatis + Spring to scan this interface and create the proxy implementation
 *
 * Naming convention (Korean enterprise):
 *   selectXxx → SELECT query  (returns data)
 *   insertXxx → INSERT query
 *   updateXxx → UPDATE query
 *   deleteXxx → soft DELETE   (UPDATE SET del_yn='Y', NOT a real SQL DELETE)
 */
@Mapper
public interface BgtMngMapper {

    /**
     * Fetch paginated list of budget records (예산 목록 조회)
     * SQL: SELECT ... FROM budget_mng WHERE del_yn='N' + dynamic filters + LIMIT/OFFSET
     * Returns: display rows (rn, jijacheNm, startMm, endMm, ntnlBgt, lclBgt, bgtSum)
     */
    List<BgtMngOutVO> selectBgtMngList(BgtMngInVO inVO);

    /**
     * Count total matching records for pagination (페이징용 전체 건수)
     * Same WHERE conditions as selectBgtMngList but returns only the total count.
     * Used to calculate: totalPages = Math.ceil(totalCount / pageSize)
     */
    int selectBgtMngListCount(BgtMngInVO inVO);

    /**
     * Fetch one record's full detail for the edit popup (상세 조회)
     * SQL: SELECT ... FROM budget_mng WHERE id = #{id} AND del_yn = 'N'
     */
    BgtMngVO selectBgtMngDetail(BgtMngInVO inVO);

    /**
     * Insert a new budget record (예산 등록)
     * id is auto-generated by PostgreSQL BIGSERIAL — no need to pass it
     */
    void insertBgtMng(BgtMngInVO inVO);

    /**
     * Update an existing budget record (예산 수정)
     * Uses <set> + <if> in XML → only updates fields that are not null
     */
    void updateBgtMng(BgtMngInVO inVO);

    /**
     * Soft delete a budget record (예산 논리삭제)
     * SQL: UPDATE budget_mng SET del_yn = 'Y', updated_at = NOW() WHERE id = #{id}
     * Does NOT physically remove the row — sets del_yn flag instead.
     * All SELECT queries filter with WHERE del_yn = 'N' to exclude deleted records.
     */
    void deleteBgtMng(BgtMngInVO inVO);
}
